<?php
 return [
			'howitworks' => 'how-it-works',
			'blocked' => 'restric',
			'allStoreCats' => 'all-store-categories',
			'allBrands' => 'all-brands',
			'blog' => 'blog',
			'sitemap' => 'sitemap',
			'business' => 'list-your-business',
			'contactUs' => 'contact-us',
			'maintenance' => 'maintenance',
			'allStores' => 'all-stores',
			'DOD' => 'deals-of-the-day',
			'aboutus' => 'about-us',
			'backend' => 'coupon-by-merchants',
			'nearme' => 'near-me',
			'allCats' => 'all-coupon-categories',
			'joinnow' => 'join-us-now',
			'faq' => 'faq',
			'referearn' => 'refer-and-earn',
			'allTags' => 'all-tags',
			'testimonial' => 'user-testimonials',
			'WhatsApp' => 'whatsapp-subscription',
   ];
