<?php
return [
 'cb_sentence' => 'Extra Upto #CBAMT #TYPE'  ,
 'cb_track_speed' => '3'  ,
 'cb_claim_days' => '90'  ,
 'dev_cookie_prefix' => 'DEWO'  ,
 'dev_sms_apiurl' => 'https://control.msg91.com/api/sendhttp.php?authkey=#API_KEY&mobiles=#NUMBER&message=#MESSAGE&sender=#SENDER&route=4&country=91'  ,
 'dev_sms_apikey' => '239993AOt9u34sGzg5bae06c7'  ,
 'dev_sms_apisender' => 'DLSWOT'  ,
 'dev_email_sender' => 'members@moola101.ga'  ,
 'dev_email_sender_name' => 'Moola101 Membership'  ,
 'dev_email_replyto' => 'contact@moola101.ga'  ,
 'social_google_clientid' => '581577053186-r9r0gih5ssprbma23nich25ol9mn92ga.apps.googleusercontent.com'  ,
 'sitemap_listing' => '25'  ,
 'website_email_alert' => 'contact@moola101.ga'  ,
 'dev_footer' => '© Copyright 2018 Moola101. All Rights Reserved.'  ,
 'website_hiw_video' => 'https://www.youtube.com/embed/zpOULjyy-n8?rel=0'  ,
 'cb_terms_todo' => 'Make sure to complete your transaction within the opened tab.
Ensure cart is empty before clicking on our website.
Add items to your cart only after the click. Click again if there\'s an error.
If for some reason your payment made on merchant page has failed, do click through our website again.
Return to our website and click through to the merchant every time you are making a new transaction.'  ,
 'reward-info' => 'Rewards from Moola101 can be withdrawn to your wallet balance or gift vouchers only. It can not be withdrawn to your bank account.'  ,
 'cb_terms_nottodo' => 'Cashback is not applicable on bulk purchases
Do not open any other comparison or coupon providing websites.
No Cashback will be provided in case you return or cancel the order.
Cashback is not applicable on shopping through credits/gift vouchers.
Accounts that try to manipulate the cashback mechanism and engage in fraud activities will be banned
Orders placed on store mobile app are not eligible for cashback '  ,
 'app_apple' => 'https://itunes.apple.com/in/app/whatsapp-messenger/id310633997?mt=8'  ,
 'hp_search_cats' => '7,8,10,11,16'  ,
 'hp_offer_count' => '15'  ,
 'whatsapp_body' => 'Here\'s your link to add our premium WhatsApp group, Happy Savings+Cashback.
#LINK

'  ,
 'app_google' => 'https://play.google.com/store/apps/details?id=com.whatsapp&hl=en_IN'  ,
 'whatsapp_number' => '919998468333'  ,
 'whatsapp_sendtxt' => 'START'  ,
 'hp_stats' => 'Coupons & Deal|6,135
Coupons Redeemed|15,325
Happy Users|3,685
Paid Cashback|₹ 5,58,365'  ,
 'hp_deal_count' => '15'  ,
 'list_store_cpn_count' => '150'  ,
 'list_store_deal_count' => '45'  ,
 'list_cat_cpn_count' => '150'  ,
 'list_dod_count' => '74'  ,
 'menu_popular_cats' => ''  ,
 'business_reasons' => 'Media, Partner, Affiliate, Promotion'  ,
 'list_brand_cpn_count' => '150'  ,
 'cb_claim_min_days' => '3'  ,
 'cb_claim_max_days' => '10'  ,
 'referral_valid_date' => '2020-12-31'  ,
 'paypal_subject' => 'You have received Cashback Payout of USD #AMOUT from #WEBSITE'  ,
 'paypal_body' => '<p>This is confirmed Payout of USD #AMOUNT.<br></p><p>SHop more to earn more.</p><p><br></p>'  ,
 'ref_min_transaction' => '1000'  ,
 'ref_cookie_days' => '5'  ,
 'seo_site_name' => 'Moola101'  ,
 'nearme_km_range' => '100'  ,
 'nearme_map_zoom' => '12'  ,
 'hp_meta_title' => '#SITENAME: Coupon, Daily Deals, Real Cashback and Promo Codes #CURRENTMONTH #CURRENTYEAR'  ,
 'hp_meta_desc' => 'Now SAVE MORE with Moola101! Get the latest and up-to-date coupons & cashback offers on some of US\'s top online shopping sites.'  ,
 'page_meta_title' => '#TITLE | #SITENAME'  ,
 'page_meta_desc' => ''  ,
 'blog_meta_title' => '#TITLE | #SITENAME'  ,
 'blog_meta_desc' => ''  ,
 'store_h1' => '#TITLE Coupon Codes & Best Deals'  ,
 'store_meta_title' => '#TITLE Coupon Codes, Promo Codes, Deals & Top Offers - #CURRENTMONTH #CURRENTYEAR  | #SITENAME'  ,
 'store_meta_desc' => 'Avail 100% Working #TITLE Coupon Codes for #CURRENTMONTH #CURRENTYEAR  | #SITENAME. Free Promo Code, Offers, Best deals, Vouchers, Discount codes, Sale, Cashback offer & more to save money on online shopping at #TITLE'  ,
 'cat_h1' => '#TITLE Coupon Codes & Promo Codes'  ,
 'cat_meta_title' => 'Best Discount Codes & Offers for #TITLE - #CURRENTMONTH #CURRENTYEAR '  ,
 'cat_meta_desc' => 'Get #TITLE Promos & Offers that 100% works. Grab Special Discount offers on #TITLE for #CURRENTMONTH #CURRENTYEAR  and save on your purchase online.'  ,
 'tag_h1' => '#TITLE Coupons & Discount Offers'  ,
 'tag_meta_title' => 'Best Discount Codes & Offers for #TITLE - #CURRENTMONTH #CURRENTYEAR '  ,
 'tag_meta_desc' => 'Get #TITLE Promos & Offers that 100% works. Grab Special Discount offers on #TITLE for #CURRENTMONTH #CURRENTYEAR  and save on your purchase online.'  ,
 'brand_h1' => '#TITLE Coupon Codes & Promo Codes'  ,
 'brand_meta_title' => 'Best Discount Codes & Offers for #TITLE - #CURRENTMONTH #CURRENTYEAR '  ,
 'brand_meta_desc' => 'Get #TITLE Promos & Offers that 100% works. Grab Special Discount offers on #TITLE for #CURRENTMONTH #CURRENTYEAR  and save on your purchase online.'  ,
 'contact_reasons' => 'Complaint, Feedback, Appreciation'  ,
 'seo_robots_txt' => 'User-agent: *
Disallow: /'  ,
 'member_contact_cats' => 'Cashback Issues
Issues with Withdrawal'  ,
 'sms_verification' => 'Y'  ,
 'coupon_meta' => 'N'  ,
 'store_cashback_links' => 'N'  ,
 'module_tags' => 'Y'  ,
 'module_brands' => 'Y'  ,
 'social_facebook' => 'https://www.facebook.com/Moola101-180760806193540/'  ,
 'social_google-plus' => 'https://www.plus.google.com/Moola101'  ,
 'social_twitter' => 'https://twitter.com/Moola101'  ,
 'social_instagram' => 'https://www.instagram.com/Moola101'  ,
 'sort_store_page' => 'clicks DESC'  ,
 'sort_category_page' => 'tb_vendors.clicks DESC'  ,
 'store_h2' => '#TITLE Discount Coupons & Offers'  ,
 'cat_h2' => '#TITLE Coupon Codes & Promo Codes'  ,
 'tag_h2' => '#TITLE Coupon Codes & Promo Codes'  ,
 'brand_h2' => '#TITLE Coupon Codes & Promo Codes'  ,
 'store-cat_h1' => 'All Stores from #STORECATEGORY'  ,
 'list_tag_cpn_count' => '150'  ,
 'social_google_secret' => '8kSXqkTfZAF8EWwVXijX-WGd'  ,
 'social_fb_clientid' => '242167743131367'  ,
 'social_fb_secret' => 'c32bc5d5447918fc9e79bc3ec1922bc7'  ,
 'referral_terms' => '<p style=\"background: unset; border-bottom: 0px;\"></p><p style=\"background: unset; border-bottom: 0px;\"><span style=\"background-color: unset;\">There is no upper limit on the number of friends you can refer and also no cap on the amount of referral bonus you can earn.</span></p><p style=\"background: unset; border-bottom: 0px;\"><span style=\"background-color: unset; font-weight: bold;\">Conditions:</span></p><p></p><ul><li style=\"background: unset; border-bottom: 0px;\">Referral bonus is applicable only on the cashback/Rewards earnings by your friend, not applicable on any bonus earnings by your friend.</li><li style=\"background: unset; border-bottom: 0px;\">We will credit bonus to your account when your friends cash back is confirmed</li></ul><div class=\"modal-footer bg-light rounded\" style=\"text-align: center;\"><span style=\"color: rgb(102, 102, 102); text-align: start;\">Example: If your friend earns Rs. 200 confirmed cash back, you will get Rs. 10 as bonus</span>					</div>'  ,
 'list_search_page' => '21'  ,
 'mlm_split' => '5'  ,
 'mlm_enabled' => 'Y'  ,
 'list_blog_count' => '5'  ,
 'coupon_import_ignore' => 'NO CODE
N/A
NA
No code'  ,
 'paypal_currency' => 'USD'  ,
 'store_default_cb' => '50'  ,
 'module_footer_categories' => 'N'  ,
 'signup_cookie_days' => '7'  ,
 'signup_popup' => 'N'  ,
 'module_adblock' => 'N'  ,
 'homepage_deals' => 'Y'  ,
 'homepage_stats' => 'Y'  ,
 'verify_mobile' => 'N'  ,
 'referral_shutdown' => 'N'  ,
 'ads_hp_main' => '<img src=\"https://lh5.ggpht.com/NFYFP2H9CCP50vAQNLa7AtCj_mbbYmOzY978fZqd31oL5qOdvXgxU3KW8ek2VgvIOvTqWY0=w728\" height=\"auto\" alt=\"\">'  ,
 'ads_hp_coupons' => '<img src=\"//lh5.ggpht.com/CztHBMfmRKhSv-_up3GCkK5R5M0TCm1czCVkVBwB0urvaHUVCEh6YtpS7DY3mcZuwC2SzX9A3w=w338\" height=\"auto\" alt=\"\">'  ,
 'ads_hp_counters' => '<img src=\"https://lh5.ggpht.com/NFYFP2H9CCP50vAQNLa7AtCj_mbbYmOzY978fZqd31oL5qOdvXgxU3KW8ek2VgvIOvTqWY0=w728\" height=\"auto\" alt=\"\">'  ,
 'ads_footer' => '<img src=\"https://lh5.ggpht.com/NFYFP2H9CCP50vAQNLa7AtCj_mbbYmOzY978fZqd31oL5qOdvXgxU3KW8ek2VgvIOvTqWY0=w728\" height=\"auto\" alt=\"\">'  ,
 'ads_storepage_main' => '<img src=\"https://lh5.ggpht.com/NFYFP2H9CCP50vAQNLa7AtCj_mbbYmOzY978fZqd31oL5qOdvXgxU3KW8ek2VgvIOvTqWY0=w728\" height=\"auto\" alt=\"\">'  ,
 'ads_storepage_bottom' => '<img src=\"https://lh5.ggpht.com/NFYFP2H9CCP50vAQNLa7AtCj_mbbYmOzY978fZqd31oL5qOdvXgxU3KW8ek2VgvIOvTqWY0=w728\" height=\"auto\" alt=\"\">'  ,
 'ads_catpage_main' => '<img src=\"https://lh5.ggpht.com/NFYFP2H9CCP50vAQNLa7AtCj_mbbYmOzY978fZqd31oL5qOdvXgxU3KW8ek2VgvIOvTqWY0=w728\" height=\"auto\" alt=\"\">'  ,
 'ads_catpage_bottom' => '<img src=\"https://lh5.ggpht.com/NFYFP2H9CCP50vAQNLa7AtCj_mbbYmOzY978fZqd31oL5qOdvXgxU3KW8ek2VgvIOvTqWY0=w728\" height=\"auto\" alt=\"\">'  ,
 'ads_sidebar_1' => '<img src=\"//lh6.ggpht.com/C-6e26E1LydXhyDCkOe1EXmb3BQ2T1IkA2AhJ-9MO-FDuWc0nyGfJI19iPP3HX9cljXFJ1Bz=w250\" height=\"auto\" alt=\"\">'  ,
 'ads_sidebar_2' => '<img src=\"//lh6.ggpht.com/C-6e26E1LydXhyDCkOe1EXmb3BQ2T1IkA2AhJ-9MO-FDuWc0nyGfJI19iPP3HX9cljXFJ1Bz=w250\" height=\"auto\" alt=\"\">'  ,
 'ads_pages_bottom' => '<img src=\"https://lh5.ggpht.com/NFYFP2H9CCP50vAQNLa7AtCj_mbbYmOzY978fZqd31oL5qOdvXgxU3KW8ek2VgvIOvTqWY0=w728\" height=\"auto\" alt=\"\">'  ,
 'hp_top_brand_count' => '25'  ,
 'refer_redeem_days' => '90'  ,
 'hp_deal_cats' => '6,7,8,9'  ,
 'hp_is_custom_brands' => 'Y'  ,
 'email_footer_addr' => '154, A2 Block, Ground Floor, Janakpuri'  ,
 'hp_custom_brands' => '1'  ,
 'list_max_cat_topstores' => '10'  ,
 'sort_deal_store_page' => 'daily_clicks DESC'  ,
 'shop_blogs' => '113,114,115'  ,
 'email_footer_links' => '',
 'email_note' => 'You are receiving this email because you have an account with DeaslWoot'  ,
 'coupon_words' => 'Best Offer, Popular Offer, Handpicked, Editors Choice, Hottest Now, Trending Offer'  ,
 'dwapp_body' => 'Extra Earning and Saving at your finger tips. Download our App at  #LINK'  ,
 'sms_send_otp_msg' => 'Your OTP is #OTP.
Use this to verify your number on Moola101'  ,
 'store_pod' => '1'  ,
 'stores_partners' => '1474,2762,4300,1231,1002,1003,1005,1523,1022,2558,1279,1001'  ,
 'maps_location' => 'https://www.google.co.in/maps/place/Chandni+Chowk,+New+Delhi,+Delhi/@28.65138,77.2141584,14z/data=!3m1!4b1!4m5!3m4!1s0x390cfd1a88dcc559:0x24fa43c081dbe51!8m2!3d28.6505942!4d77.2303284'  ,
 'corporate_address' => 'Moola101 PVT LTD.
Singapore'  ,
 'social_youtube' => 'https://www.youtube.com/'  ,
 'social_linkedin' => 'https://www.linkedin.com/company/Moola101/'  ,
 'dod_deal_cats' => '101'  ,
 'dod_ajax_limit' => '16'  ,
 'hpdod_ajax_limit' => '16'  ,
 'mobile_app_header_style' => 'default'  ,
 'mobile_app_button_style' => 'default'  ,
 'mobile_app_background_color' => '#e7e7e7'  ,
 'mobileApp_brandPrimary_android' => '#3F51B5'  ,
 'mobileApp_brandPrimary_ios' => '#007aff'  ,
 'mobileApp_toolbarDefaultBg' => '#F8F8F8'  ,
 'hp_hero_background' => 'http://moola101.ga/public_assets/images/Main_banner.png'  ,
 'hp_featured_store_count' => '1'  ,
'cnf_maintenance' 			=> '',
];
