<?php
return [
'cnf_appname' 			=> 'Moola101',
'cnf_appdesc' 			=> 'Moola101 Admin CMS',
'cnf_comname' 			=> 'Moola101',
'cnf_email' 			=> 'contact@moola101.com',
'cnf_metakey' 			=> 'my site , my company  , Larvel Crud',
'cnf_metadesc' 		=> 'Hello THere',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'auto',
'cnf_multilang' 		=> '0',
'cnf_lang' 			=> 'en',
'cnf_regist' 			=> 'true',
'cnf_front' 			=> 'false',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '',
'cnf_recaptchaprivatekey' => '',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'Header_logo.png',
'cnf_favicon' 			=> 'favicon.PNG',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '122.171.167.20',
'cnf_restrictrefer' 		=> '',
'cnf_restricttime' 		=> '5 Days',
'cnf_restrictcount' 		=> '10',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> '',
'cnf_date' 			=> 'd-m-y',
'cnf_currencyname' 			=> '$',
'cnf_currencysuffix' 			=> '',
'cnf_maintenance' 			=> 'false',
'cnf_recaptchapublickey' => '6LcBeoYUAAAAAM8kKOmoyExTS-IzovVmSTM0Bs6Y',
'cnf_recaptchaprivatekey' => '6LcBeoYUAAAAAAMno3zRYmlER3VFBuJ-rcG4Jz_N',
];
